import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-[linear-gradient(to_bottom,#0A253B,#000000,#000000)] antialiased`}
      >
        <div className="app-content relative h-screen max-w-md mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
